### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by morihey** [stackroute/atom-css-spy#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Microsoft Windows 10 Pro
**Thrown From**: [css-spy](https://github.com/stackroute/atom-css-spy) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /C:/Users/georg/.atom/packages/css-spy/lib/css-spy.coffee:40

TypeError: Cannot read property 'getPath' of undefined
    at file:///C:/Users/georg/.atom/packages/css-spy/lib/css-spy.coffee:24:27
    at Emitter.module.exports.Emitter.emit (C:\Users\georg\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at C:\Users\georg\AppData\Local\atom\app-1.3.2\resources\app.asar\src\text-editor.js:210:32
    at Emitter.module.exports.Emitter.emit (C:\Users\georg\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (C:\Users\georg\AppData\Local\atom\app-1.3.2\resources\app.asar\src\display-buffer.js:313:20)
    at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (C:\Users\georg\AppData\Local\atom\app-1.3.2\resources\app.asar\src\display-buffer.js:1224:19)
    at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (C:\Users\georg\AppData\Local\atom\app-1.3.2\resources\app.asar\src\display-buffer.js:1186:19)
    at C:\Users\georg\AppData\Local\atom\app-1.3.2\resources\app.asar\src\display-buffer.js:5:61
    at Emitter.module.exports.Emitter.emit (C:\Users\georg\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (C:\Users\georg\AppData\Local\atom\app-1.3.2\resources\app.asar\src\tokenized-buffer.js:315:22)
    at C:\Users\georg\AppData\Local\atom\app-1.3.2\resources\app.asar\src\tokenized-buffer.js:269:26
    at C:\Users\georg\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\underscore-plus\node_modules\underscore\underscore.js:666:47
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "hyperclick-php"
    ],
    "ignoredNames": [
      ".settings",
      ".project",
      ".buildpath"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.14
css-spy, v0.2.0
minimap, v4.19.0
php-integrator-annotations, v0.2.2
php-integrator-autocomplete-plus, v0.3.0
php-integrator-base, v0.3.1
php-integrator-navigation, v0.2.4
php-integrator-tooltips, v0.2.1
pigments, v0.19.5

# Dev
No dev packages
```

**Comment by prateekreddy** [comment]
Hi @morihey, I am unable to see the steps to reproduce the error, I tried testing the package with atom 1.3.2 and Windows 10 pro but could not reproduce this error. Can you please elaborate on how to reproduce it ?
