### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Kbam7** [stackroute/atom-css-spy#14]
I discovered that i started getting this error when i uninstalled the Atom package "activate-power-mode". Upon reinstalling "activate-power-mode" the errors stopped.

**UPDATE**
All of a sudden i started getting this error again. I have not made any changes. I am unable to use css-spy as this error is very annoying. I also noticed "activate-power-mode" doesn't work anymore.

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Ubuntu 16.04.1
**Thrown From**: [css-spy](https://github.com/stackroute/atom-css-spy) package, v0.6.0
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/kbam7/.atom/packages/css-spy/lib/provider.coffee:76

TypeError: Cannot read property 'length' of undefined
    at /home/kbam7/.atom/packages/css-spy/lib/provider.coffee:76:9
    at IncomingMessage.<anonymous> (/home/kbam7/.atom/packages/css-spy/lib/provider.coffee:57:13)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "packagesWithKeymapsDisabled": []
  }
}
```
### Installed Packages

``` coffee
# User
api-docs, v0.0.6 (active)
auto-id-class, v0.2.6 (active)
autoclose-html, v0.23.0 (active)
autocomplete-html-entities, v0.1.0 (active)
css-snippets, v1.0.0 (active)
css-spy, v0.6.0 (active)
dark-flat-ui, v1.2.4 (inactive)
git-plus, v5.18.0 (active)
git-time-machine, v1.5.3 (inactive)
graphite-ui, v0.15.1 (inactive)
inline-messenger, v1.2.8 (active)
linter, v1.11.18 (active)
linter-csslint, v1.3.3 (active)
linter-htmlhint, v1.3.0 (active)
linter-php, v1.2.0 (active)
norminette-linter, v0.2.0 (active)
platformio-ide-terminal, v2.2.0 (active)
quick-docs, v0.1.0 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
seti-ui-red, v0.13.0 (inactive)
sync-settings, v0.7.2 (active)
unicorn-ui, v1.2.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Kbam7** [comment]
I discovered that i started getting this error when i uninstalled the Atom package "activate-power-mode". Upon reinstalling "activate-power-mode" there errors stopped.

**Comment by kumamaki** [comment]
Same issue for me

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [css-spy](https://github.com/stackroute/atom-css-spy) package 0.6.0


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /data/LinuxStuff/Config/.atom/packages/css-spy/lib/provider.coffee:76

TypeError: Cannot read property 'length' of undefined
    at /packages/css-spy/lib/provider.coffee:76:9
    at /packages/css-spy/lib/provider.coffee:57:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -1:45.3.0 core:move-right (input.hidden-input)
     -1:45.1.0 core:move-left (input.hidden-input)
  5x -1:44.8.0 core:select-left (input.hidden-input)
     -1:41.4.0 core:save (input.hidden-input)
     -1:20.9.0 autocomplete-plus:confirm (input.hidden-input)
  2x -1:20.2.0 core:save (input.hidden-input)
  4x -0:31.1.0 core:move-left (input.hidden-input)
     -0:30.2.0 editor:delete-line (input.hidden-input)
  3x -0:30 core:move-up (input.hidden-input)
     -0:28.5.0 editor:delete-line (input.hidden-input)
  3x -0:28.3.0 core:move-down (input.hidden-input)
     -0:27.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:27.1.0 core:move-left (input.hidden-input)
  6x -0:26.9.0 core:backspace (input.hidden-input)
     -0:24.7.0 core:save (input.hidden-input)
     -0:15 core:move-to-bottom (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
aligner 0.22.3 
aligner-css 1.2.0 
aligner-php 1.0.0 
aligner-scss 1.1.0 
angularjs 0.4.0 
atom-beautify 0.29.17 
atom-brackets-glow 0.4.0 
atom-material-syntax 1.0.2 
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.9 
atom-move-line 0.3.3 
atom-ng-attr-hint 2.1.0 
atom-panda-syntax 0.18.0 
atom-terminal 0.8.0 
atom-ternjs 0.17.2 
auto-indent 0.5.0 
autocomplete-html-entities 0.1.0 
autocomplete-json 5.2.0 
autocomplete-paths 1.0.5 
autocomplete-php 0.3.7 
chester-atom-syntax 0.1.1 
color-picker 2.2.5 
creative-dark-syntax 1.1.0 
css-declaration-sorter 0.4.0 
css-specificity 0.2.2 
css-spy 0.6.0 
git-plus 7.3.0 
git-time-machine 1.5.6 
gl-light-syntax 2.2.0 
goto-definition 1.1.19 
guess-indent 0.1.0 
hey-pane 0.1.0 
highlight-line 0.12.0 
highlight-selected 0.12.0 
html-to-css 0.2.2 
imdone-atom 2.1.18 
indent-helper 0.2.0 
isotope-light-ui 2.2.6 
isotope-ui 2.7.1 
json-colorer 1.0.0 
language-ejs 0.4.0 
language-postcss 1.3.0 
less-than-slash 0.16.0 
linter 1.11.23 
linter-eslint 8.1.2 
linter-jshint 3.0.2 
linter-php 1.3.1 
linter-sass-lint 1.7.4 
linter-stylelint 3.9.0 
local-history 4.0.1 
material-ui 1.0.9 
merge-conflicts 1.4.4 
new-tab 0.5.3 
nord-atom-ui 0.10.1 
nucleus-dark-ui 0.11.0 
open-in-browser 0.4.7 
php-cs-fixer 4.1.0 
pigments 0.39.0 
project-manager 3.3.3 
project-view 0.6.2 
pulley-syntax 2.0.3 
remember-folds 0.3.0 
Remote-FTP 0.10.5 
sensible-tab 1.0.0 
slack-ui 0.8.0 
unfancy-file-icons 0.10.0 
```
