### ISSUE TITLE
Failed to activate the css-spy package

### ISSUE THREAD

**Issue by danielbayley** [stackroute/atom-css-spy#17]
**Atom**: 1.14.0-beta3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [css-spy](https://github.com/stackroute/atom-css-spy) package 0.6.0

### Stack Trace

Failed to activate the css-spy package

```
At ENOENT: no such file or directory, open '/Users/Dan/Library/Application Support/Atom/dev/packages,/Users/Dan/Library/Application Support/Atom/packages/css-spy/grammar/class-add.cson'

Error: ENOENT: no such file or directory, open '/Users/Dan/Library/Application Support/Atom/dev/packages,/Users/Dan/Library/Application Support/Atom/packages/css-spy/grammar/class-add.cson'
  at Error (native)
  at Object.fs.openSync (fs.js:640:18)
  at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
  at Object.fs.readFileSync (fs.js:508:33)
  at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
  at CSON.parseCSONFile (/packages/css-spy/node_modules/cson/out/lib/cson.js:332:23)
  at CSON.load (/packages/css-spy/node_modules/cson/out/lib/cson.js:141:19)
  at /packages/css-spy/lib/css-spy.coffee:7:18)
  at /packages/css-spy/lib/css-spy.coffee:1:1)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Function.Module._load (/packages/modular-snippets/node_modules/require-cson/register.js:9:15)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
  at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
  at /app.asar/src/package.js:190:32
  at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
  at /app.asar/src/package.js:183:26
  at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
  at /app.asar/src/package-manager.js:531:29
  at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
  at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
  at /app.asar/src/atom-environment.js:814:28

```

### Commands

```
     -2:49.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-predawn-syntax.theme-predawn-ui)
     -2:47.2.0 env-from-shell:copy (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-predawn-syntax.theme-predawn-ui)
```

### Non-Core Packages

```
advanced-open-file 0.16.5 (dev)
atom-beautify 0.28.15 (dev)
open-terminal-here 2.3.0 
atom-webbrowser 2.1.4 (dev)
atomic-spinner 0.0.0 (dev)
base-ui undefined (dev)
block-and-line-comment 0.4.0 (dev)
browser-plus 0.0.87 (dev)
build 0.65.0 (dev)
color-picker 2.1.1 (dev)
contextual-preview 0.0.0 (dev)
copy-path-plus 0.1.0 (dev)
custom-app-icon 0.2.3 (dev)
disable-menus 0.0.0 (dev)
fall-syntax 0.0.0 (dev)
finder-fixes 0.0.0 (dev)
ghost 0.0.0 (dev)
git-plus 5.16.2 (dev)
gitkraken 0.4.2 (dev)
hyperclick-npm undefined (dev)
imdone-atom 2.1.18 (dev)
language-applescript 0.2.2 (dev)
language-cson undefined (dev)
language-extendscript 0.0.0 (dev)
language-javascript-jxa 0.2.8 (dev)
language-posthtml 0.0.0 (dev)
mnml-syntax 0.0.0 (dev)
modular-keymaps 0.1.5 (dev)
modular-snippets 0.1.3 (dev)
mute-syntax undefined (dev)
open-recent 5.0.0 (dev)
pattern-preview undefined (dev)
plist-converter 0.1.6 (dev)
postcss-sorting 2.4.0 (dev)
predawn-syntax 1.0.4 (dev)
predawn-ui 1.0.2 (dev)
project-config 0.0.0 (dev)
project-manager 2.9.7 (dev)
project-plus 0.8.2 (dev)
project-templates undefined (dev)
script 3.11.1 (dev)
source-preview 0.5.0 (dev)
source-preview-decaf 0.1.0 (dev)
source-preview-less 0.1.6 (dev)
source-preview-markdown 0.1.1 (dev)
source-preview-marko 0.1.2 (dev)
source-preview-postcss 0.1.4 (dev)
source-preview-posthtml 0.0.0 (dev)
source-preview-pug 0.2.0 (dev)
source-preview-sass 0.1.6 (dev)
source-preview-slm 0.1.0 (dev)
source-preview-stylus 0.1.7 (dev)
sync-settings 0.6.0 (dev)
terminal-panel 1.14.1 (dev)
text-manipulation 0.6.0 (dev)
transpile 0.1.4 (dev)
transpile-cson 2.0.1 (dev)
css-converter 0.0.0 
transpile-decaf 0.1.3 (dev)
transpile-html2pug undefined (dev)
transpile-js2coffee undefined (dev)
transpile-lebab 0.0.0 (dev)
tree-view-search-bar 0.1.1 (dev)
tree-view-symlink undefined (dev)
url-utils 0.2.1 (dev)
advanced-open-file 0.16.5 (dev)
ansible-snippets 0.2.0 
api-docs 0.0.6 
apm-publish 0.3.0 
asciidoc-preview 2.7.1 
Atom-Bash-Snippets 0.0.3 
atom-beautify 0.28.15 (dev)
atom-calca 0.3.1 
atom-css-class-checker 0.4.3 
atom-css-unit-converter 1.1.1 
atom-html-preview 0.1.22 
atom-jasmine 0.8.1 
atom-jq 0.7.0 
atom-lupa 0.7.32 
atom-react-es2015-snippets 1.1.2 
atom-react-native-autocomplete 0.0.27 
atom-react-native-css 1.1.3 
atom-reverser 2.6.0 
atom-smart-tabs 0.1.0 
atom-sticky-cursor 0.0.8 
atom-ternjs 0.17.0 
atom-touch-events 0.23.0 
atom-typescript undefined 
atom-webbrowser 2.1.4 (dev)
atom-xcode 0.1.3 
atom-yeoman 0.3.15 
auto-detect-indentation 1.3.0 
auto-run 0.2.1 
auto-update-plus 0.2.0 
autoclose-html 0.23.0 
autocomplete-date 0.4.0 
autocomplete-html-entities 0.1.0 
autocomplete-json undefined 
autocomplete-modules 1.6.7 
autocomplete-paths 1.0.5 
autocomplete-ruby 0.2.5 
autocomplete-sass 0.1.0 
autocomplete-swift 1.0.3 
autohide-tree-view 0.25.1 
autoprefixer 3.6.1 
bezier-curve-editor 0.7.2 
block-and-line-comment 0.4.0 (dev)
browser-plus 0.0.87 (dev)
build 0.65.0 (dev)
build-coffee 0.6.4 
build-decaffeinate 0.1.9 
build-dockerfile 1.0.1 
build-lessc 0.5.5 
build-make 0.13.0 
build-markdown 1.1.0 
build-npm-apm 0.12.0 
build-osa 0.5.8 
build-rake 0.1.1 
build-sassc 0.6.0 
build-stylus 0.6.3 
build-sugarss 0.4.9 
build-xcodebuild 0.2.0 
busy 0.7.0 
calc 0.4.0 
captain-hook 0.0.1 
chmod 0.1.1 
circle-ci 0.10.1 
clean-context-menu 0.3.2 
clipboard-plus 0.5.1 
color-picker 2.1.1 (dev)
context-git 0.14.1 
contextual-preview 0.0.0 (dev)
css-snippets 1.1.0 
css-spy 0.6.0 
custom-app-icon 0.2.3 (dev)
custom-title 1.0.1 
dash 1.7.0 
default-language 0.3.0 
dict 0.2.3 
dictionary 0.5.0 
disable-grammars 0.1.1 
disable-keybindings 0.6.0 
distribute-panes 0.1.0 
dockerletion 0.2.0 
double-tag 0.4.0 
dracula-theme 2.0.0 
duotone-dark-sea-syntax 2.1.0 
duotone-dark-syntax 2.1.0 
duplicate-line-or-selection 0.9.0 
eclectic-syntax 0.2.1 
editorconfig 2.2.0 
emmet 2.4.3 
env-from-shell 0.3.0 
expand-region 0.2.6 
external-open 0.6.3 
file-icons 2.0.15 
file-templates 0.2.0 
file-type-icons 1.3.3 
file-types 0.5.5 
firewatch-syntax 1.1.1 
flex-tool-bar 0.11.0 
flexbox-snippets 0.3.0 
flexible-ui 0.10.7 
gfm-pdf 0.3.4 
gist 0.3.1 
git-diff-details 1.4.0 
git-history 3.2.0 
git-plus 5.16.2 (dev)
git-travel 0.1.4 
gitkraken 0.4.2 (dev)
gruvbox 1.0.7 
hey-pane 0.2.0 
highlight-selected 0.12.0 
html-id-class-snippets 1.4.1 
html-to-css 0.2.2 
html2jade-plus 1.0.0 
html2slim 0.4.1 
hyperclick 0.0.40 
icon-fonts 2.13.0 
imdone-atom 2.1.18 (dev)
imdone-atom-github 0.1.11 
indent-guide-improved 1.4.12 
isotope-light-ui 2.2.6 
isotope-ui 2.7.1 
jQuery 1.2.5 
js-hyperclick 1.10.1 
language-ansible 0.2.1 
language-apache 1.7.0 
language-applescript 0.2.2 (dev)
language-babel 2.54.1 
language-csv 1.1.2 
language-docker 1.1.7 
language-dots 0.0.4 
language-env 0.2.0 
language-generic-config 1.3.0 
language-gitignore 0.3.0 
language-ignore 1.5.2 
language-ini 1.17.0 
language-javascript-jsx 0.3.7 
language-javascript-jxa 0.2.8 (dev)
language-markdown 0.19.1 
language-marko 2.9.0 
language-postcss 1.3.0 
language-pug 0.0.19 
language-slm 0.5.0 
language-svg 0.9.2 
language-swift 0.5.0 
language-vue 0.21.2 
lines 0.13.1 
linter 1.11.21 
linter-ansible-linting 1.2.2 
linter-ansible-syntax 1.1.1 
linter-coffeelint 1.2.1 
linter-docker 0.1.4 
linter-doiuse 0.2.3 
linter-eslint 8.1.0 
linter-flow 5.5.0 
linter-htmlhint 1.3.1 
linter-js-yaml 1.2.6 
linter-jscs 4.1.1 
linter-jshint 3.0.2 
linter-jsonlint 1.3.0 
linter-less 2.6.0 
linter-markdown 3.1.0 
linter-perl 0.8.0 
linter-pug 1.3.0 
linter-remark 2.1.0 
linter-rubocop 0.5.3 
linter-sass-lint 1.7.4 
linter-scss-lint 3.0.4 
linter-shellcheck 1.4.3 
linter-stylelint 3.8.0 
linter-stylint 2.2.6 
linter-swiftc 2.0.0 
linter-swiftlint 1.2.1 
linter-tidy 2.3.0 
linter-write-good 0.8.0 
linter-xmllint 1.4.0 
linter-xo 0.21.2 
livereload 0.4.4 
make-executable 0.1.1 
markdown-folder 0.5.0 
markdown-pdf 1.5.0 
markdown-preview-enhanced 0.9.7 
markdown-table-formatter 2.8.4 
markdown-toc 0.4.2 
markdown-writer 2.6.3 
medium-upload 0.1.2 
merge-conflicts 1.4.4 
modular-keymaps 0.1.5 (dev)
modular-snippets 0.1.3 (dev)
monocolor-amber-syntax 1.0.0 
monocolor-lime-syntax 1.0.0 
monocolor-orange-syntax 1.0.0 
move-status-items 0.0.11 
native-ui 0.20.4 
navigate 0.1.17 
nebula-syntax 0.4.4 
nebula-ui 0.6.0 
npm-helper 0.8.9 
nucleus-dark-ui 0.10.22 
open-project-in-tower 1.4.0 
open-recent 5.0.0 (dev)
open-terminal-here 2.3.0 
package-settings 1.1.0 
pain-split 1.4.0 
pandoc 0.2.2 
pane-split-moves-tab 0.1.0 
pdf-view undefined 
pigments 0.39.0 
pinned-tabs 0.4.2 
plist-converter 0.1.6 (dev)
polymorph-ui 1.8.8 
postcss-sorting 2.9.0 (dev)
predawn-syntax 1.0.4 (dev)
predawn-ui 1.0.2 (dev)
preview 0.17.0 
project-manager 2.9.7 (dev)
project-plus 0.8.2 (dev)
react 0.16.2 
react-redux-atom-snippets 0.7.2 
react-snippets 0.6.2 
regex-railroad-diagram 0.16.0 
rest-client 1.3.1 
rulerz 0.4.1 
script 3.11.1 (dev)
scroll-sync 0.1.5 
sequential-command 0.3.0 
seti-icons 1.3.4 
seti-syntax 1.1.2 
seti-ui 1.6.1 
smart-quotes-plus 2.1.0 
solid-completions 2.0.0 
sort-lines 0.14.0 
source-preview 0.5.0 (dev)
source-preview-babel 0.2.1 
source-preview-less 0.1.6 (dev)
source-preview-markdown 0.1.1 (dev)
source-preview-postcss 0.1.4 (dev)
source-preview-posthtml 0.0.0 (dev)
source-preview-pug 0.2.0 (dev)
source-preview-react 0.2.0 
source-preview-sass 0.1.6 (dev)
source-preview-slm 0.1.0 (dev)
source-preview-stylus 0.1.7 (dev)
sourcerer 2.0.0 
split-diff 1.1.2 
stylefmt 4.0.0 
Stylus 3.1.0 
Sublime-Style-Column-Selection 1.7.3 
svg-preview 0.11.0 
svgo 2.6.0 
sync-settings 0.6.0 (dev)
synced-sidebar 0.4.3 
tab-control 0.6.9 
table-editor 0.2.2 
tablr 1.8.1 
tabs-to-spaces 1.0.3 
takana-atom 0.1.0 
terminal-panel 1.14.1 (dev)
test-status 1.0.0 
text-manipulation 0.6.0 (dev)
todo-show 1.9.0 
toggle-quotes 1.0.0 
tool-bar 1.0.1 
transform 0.4.0 
transpile 0.1.4 (dev)
transpile-cson 2.0.1 (dev)
transpile-decaf 0.1.3 (dev)
transpile-js2coffee 0.1.2 (dev)
travis-ci-status 1.3.0 
tree-view-autoresize 1.5.0 
tree-view-breadcrumb 0.8.1 
tree-view-git-projects 0.5.0 
tree-view-git-status 1.3.0 
tree-view-search-bar 0.1.2 (dev)
tree-view-sort 0.6.0 
twilight-syntax-theme 0.1.1 
unity-ui 2.1.8 
url-utils 0.2.1 (dev)
vue-snippets 0.6.0 
wakatime 6.0.13 
wordcount undefined 
Zen 0.16.4 
zip-folder 3.2.0 
```

**Comment by danielbayley** [comment]
I should add that this **only happens** when I load Atom **in dev mode**… which is very strange considering I haven't forked this package to work on.

**Comment by ghost** [comment]
First time trying atom. Wanted css class autocomplete in html without needing to have the css file opened in another tab, installed this package and bum! error... don´t know what is dev mode

**Comment by bgarrant** [comment]
Any chance you can help us fix this issue?

**Comment by bgarrant** [comment]
**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.3
**Thrown From**: [css-spy](https://github.com/stackroute/atom-css-spy) package 0.6.0


### Stack Trace

Failed to activate the css-spy package

```
At Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
    at Object.makeWordList (/packages/css-spy/lib/provider.coffee:34:38)
    at Object.module.exports.watcherFunction (/packages/css-spy/lib/css-spy.coffee:50:22)
    at /packages/css-spy/lib/css-spy.coffee:25:24
    at Workspace.observeTextEditors (<embedded>:28163:15)
    at Object.activate (/packages/css-spy/lib/css-spy.coffee:23:45)
    at Package.module.exports.Package.activateNow (<embedded>:72535:25)
    at <embedded>:72507:38
    at Package.module.exports.Package.measure (<embedded>:72379:21)
    at <embedded>:72500:32
    at Package.module.exports.Package.activate (<embedded>:72497:40)
    at PackageManager.activatePackage (<embedded>:25356:42)
    at config.transactAsync (<embedded>:25331:36)
    at Config.module.exports.Config.transactAsync (<embedded>:22003:24)
    at PackageManager.activatePackages (<embedded>:25329:23)
    at PackageManager.activate (<embedded>:25308:50)
    at <embedded>:1103:36

```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-ide-ui 0.8.1 
css-spy 0.6.0 
file-icons 2.1.16 
ide-css 0.2.0 
language-antlers 0.3.5 
language-twig 1.6.3 
less-than-slash 0.18.0 
pigments 0.40.2 
rainglow 1.5.5 
terminal-tab 0.4.0 
```

**Comment by rolzing** [comment]
1. installing css-spy package
2. alert shows "Failed to activate the css-spy package" 

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [css-spy](https://github.com/stackroute/atom-css-spy) package 0.6.0


### Stack Trace

Failed to activate the css-spy package

```
At Cannot read property 'text.html.basic' of undefined

TypeError: Cannot read property 'text.html.basic' of undefined
    at Object.module.exports.watcherFunction (/packages/css-spy/lib/css-spy.coffee:43:48)
    at /packages/css-spy/lib/css-spy.coffee:25:24
    at Workspace.observeTextEditors (<embedded>:28519:59)
    at Object.activate (/packages/css-spy/lib/css-spy.coffee:23:45)
    at Package.activateNow (<embedded>:72542:33)
    at measure (<embedded>:72518:33)
    at Package.measure (<embedded>:72400:25)
    at activationPromise.Promise (<embedded>:72512:20)
    at Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:72510:38)
    at PackageManager.activatePackage (<embedded>:25755:42)
    at config.transactAsync (<embedded>:25730:36)
    at Config.transactAsync (<embedded>:22351:28)
    at PackageManager.activatePackages (<embedded>:25728:23)
    at PackageManager.activate (<embedded>:25707:50)
    at loadStatePromise.loadState.then (<embedded>:1111:27)
    at <anonymous>:null:null

```

### Commands

```
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
atom-beautify 0.32.2 
atom-dark-fusion-syntax 2.2.1 
atom-typescript 12.4.1 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
css-spy 0.6.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.19 
gruvbox 1.0.7 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
native-ui 0.26.1 
platformio-ide-terminal 2.8.1 
prettier-atom 0.53.0 
project-manager 3.3.5 
teletype 0.13.2 
unity-ui 2.1.11 
zentabs 0.8.9 
```

**Comment by owenfranssen** [comment]
[Enter steps to reproduce:]

1. On Atom startup
2. alert shows "Failed to activate the css-spy package"

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [css-spy](https://github.com/stackroute/atom-css-spy) package 0.6.0


### Stack Trace

Failed to activate the css-spy package

```
At Cannot read property 'text.html.basic' of undefined

TypeError: Cannot read property 'text.html.basic' of undefined
    at Object.module.exports.watcherFunction (/packages/css-spy/lib/css-spy.coffee:43:48)
    at /packages/css-spy/lib/css-spy.coffee:25:24
    at Workspace.observeTextEditors (<embedded>:28519:59)
    at Object.activate (/packages/css-spy/lib/css-spy.coffee:23:45)
    at Package.activateNow (<embedded>:72542:33)
    at measure (<embedded>:72518:33)
    at Package.measure (<embedded>:72400:25)
    at activationPromise.Promise (<embedded>:72512:20)
    at Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:72510:38)
    at PackageManager.activatePackage (<embedded>:25755:42)
    at config.transactAsync (<embedded>:25730:36)
    at Config.transactAsync (<embedded>:22351:28)
    at PackageManager.activatePackages (<embedded>:25728:23)
    at PackageManager.activate (<embedded>:25707:50)
    at loadStatePromise.loadState.then (<embedded>:1111:27)
    at <anonymous>:null:null

```

### Commands

```
```

### Non-Core Packages

```
atom-browsersync 0.2.0 
atom-commander 0.11.0 
atom-ide-ui 0.11.1 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-wrap-in-tag 0.6.0 
autoclose-html 0.23.0 
browser-refresh 0.9.0 
busy-signal 1.4.3 
color-picker 2.3.0 
css-spy 0.6.0 
double-tag 1.4.1 
file-icons 2.1.19 
ide-css 0.3.0 
ide-html 0.4.2 
ide-json 0.2.1 
ide-php 0.7.14 
ide-typescript 0.7.6 
intentions 1.1.5 
language-liquid 0.6.0 
language-markdown 0.25.1 
less-than-slash 0.18.0 
linter 2.2.0 
linter-coffeelint 2.0.0 
linter-csslint 2.0.1 
linter-eslint 8.4.1 
linter-jsonlint 1.3.0 
linter-markdown 5.2.1 
linter-php 1.5.1 
linter-sass-lint 1.8.3 
linter-tidy 2.3.1 
linter-ui-default 1.7.1 
markdown-pdf 2.1.0 
markdown-scroll-sync 2.1.2 
open-in-browsers 0.0.30 
package-sync 1.1.0 
platformio-ide-terminal 2.8.1 
project-manager 3.3.5 
project-view 0.6.2 
remote-ftp 2.1.4 
remote-sync 4.1.8 
simple-drag-drop-text 0.4.0 
structure-view 0.2.1 
```
