### ISSUE TITLE
Failed to activate the css-spy package

### ISSUE THREAD

**Issue by satish-sukumar** [stackroute/atom-css-spy#2]
[Enter steps to reproduce below:]

Failed on activation of the plugin after upgrade to 0.2.1

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.1
**Thrown From**: [css-spy](https://github.com/stackroute/atom-css-spy) package, v0.2.1

### Stack Trace

Failed to activate the css-spy package

```
At Cannot read property '0' of null

TypeError: Cannot read property '0' of null
    at /Users/satishsukumar/.atom/packages/css-spy/lib/provider.coffee:23:42
    at /Users/satishsukumar/Downloads/atomic/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:858:18
    at TextBuffer.module.exports.TextBuffer.scanInRange (/Users/satishsukumar/Downloads/atomic/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:896:9)
    at TextBuffer.module.exports.TextBuffer.scan (/Users/satishsukumar/Downloads/atomic/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:854:19)
    at TextEditor.module.exports.TextEditor.scan (/Users/satishsukumar/Downloads/atomic/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2182:26)
    at Object.module.exports.makeWordList (/Users/satishsukumar/.atom/packages/css-spy/lib/provider.coffee:21:12)
    at /Users/satishsukumar/.atom/packages/css-spy/lib/css-spy.coffee:15:18
    at Workspace.module.exports.Workspace.observeTextEditors (/Users/satishsukumar/Downloads/atomic/Atom.app/Contents/Resources/app.asar/src/workspace.js:282:9)
    at Object.module.exports.activate (/Users/satishsukumar/.atom/packages/css-spy/lib/css-spy.coffee:13:39)
    at Package.module.exports.Package.activateNow (/Users/satishsukumar/Downloads/atomic/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Users/satishsukumar/Downloads/atomic/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Users/satishsukumar/Downloads/atomic/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Users/satishsukumar/Downloads/atomic/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Users/satishsukumar/Downloads/atomic/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/satishsukumar/Downloads/atomic/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
    at /Users/satishsukumar/Downloads/atomic/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/Users/satishsukumar/Downloads/atomic/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Users/satishsukumar/Downloads/atomic/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/Users/satishsukumar/Downloads/atomic/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "followSymlinks": false
  }
}
```

### Installed Packages

```coffee
# User
css-spy, v0.2.1

# Dev
No dev packages
```

**Comment by prateekreddy** [comment]
Hi @satish-sukumar, the bug is now fixed in v0.2.2.
