### ISSUE TITLE
Failed to activate the css-spy package

### ISSUE THREAD

**Issue by amitabhaghosh197** [stackroute/atom-css-spy#24]
TypeError: Cannot read property 'text.html.basic' of undefined
    at Object.module.exports.watcherFunction (file:///C:/Users/Da mirecle/.atom/packages/css-spy/lib/css-spy.coffee:25:10)
    at file:///C:/Users/Da mirecle/.atom/packages/css-spy/lib/css-spy.coffee:17:8
    at Workspace.observeTextEditors (C:\Users\Da mirecle\AppData\Local\atom\app-1.27.1\resources\app\src\workspace.js:639:59)
    at Object.activate (file:///C:/Users/Da mirecle/.atom/packages/css-spy/lib/css-spy.coffee:16:39)
    at Package.activateNow (C:\Users\Da mirecle\AppData\Local\atom\app-1.27.1\resources\app\src\package.js:230:33)
    at measure (C:\Users\Da mirecle\AppData\Local\atom\app-1.27.1\resources\app\src\package.js:206:33)
    at Package.measure (C:\Users\Da mirecle\AppData\Local\atom\app-1.27.1\resources\app\src\package.js:88:25)
    at activationPromise.Promise (C:\Users\Da mirecle\AppData\Local\atom\app-1.27.1\resources\app\src\package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (C:\Users\Da mirecle\AppData\Local\atom\app-1.27.1\resources\app\src\package.js:198:38)
    at PackageManager.activatePackage (C:\Users\Da mirecle\AppData\Local\atom\app-1.27.1\resources\app\src\package-manager.js:695:42)
    at C:\Users\Da mirecle\AppData\Local\atom\app-1.27.1\resources\app\node_modules\settings-view\lib\package-manager.js:491:35
    at exit (C:\Users\Da mirecle\AppData\Local\atom\app-1.27.1\resources\app\node_modules\settings-view\lib\package-manager.js:128:22)
    at triggerExitCallback (C:\Users\Da mirecle\AppData\Local\atom\app-1.27.1\resources\app\src\buffered-process.js:267:15)
    at ChildProcess.process.on (C:\Users\Da mirecle\AppData\Local\atom\app-1.27.1\resources\app\src\buffered-process.js:297:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by freslylumban** [comment]
TypeError: Cannot read property 'text.html.basic' of undefined
    at Object.module.exports.watcherFunction (C:\Users\Fresly\.atom\packages\css-spy\lib\css-spy.coffee:43:48)
    at C:\Users\Fresly\.atom\packages\css-spy\lib\css-spy.coffee:25:24
    at Workspace.observeTextEditors (<embedded>:28752:59)
    at Object.activate (C:\Users\Fresly\.atom\packages\css-spy\lib\css-spy.coffee:23:45)
    at Package.activateNow (<embedded>:74368:33)
    at measure (<embedded>:74344:33)
    at Package.measure (<embedded>:74226:25)
    at activationPromise.Promise (<embedded>:74338:20)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:74336:38)
    at PackageManager.activatePackage (<embedded>:25986:42)
    at <embedded>:57836:35
    at exit (<embedded>:57473:22)
    at triggerExitCallback (<embedded>:131191:15)
    at ChildProcess.process.on (<embedded>:131221:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

**Comment by Mgldvd** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.3
**Thrown From**: [css-spy](https://github.com/stackroute/atom-css-spy) package 0.6.0


### Stack Trace

Failed to activate the css-spy package

```
At Cannot read property 'text.html.basic' of undefined

TypeError: Cannot read property 'text.html.basic' of undefined
    at Object.module.exports.watcherFunction (/packages/css-spy/lib/css-spy.coffee:43:48)
    at /packages/css-spy/lib/css-spy.coffee:25:24
    at Workspace.observeTextEditors (<embedded>:28752:59)
    at Object.activate (/packages/css-spy/lib/css-spy.coffee:23:45)
    at Package.activateNow (<embedded>:74368:33)
    at measure (<embedded>:74344:33)
    at Package.measure (<embedded>:74226:25)
    at activationPromise.Promise (<embedded>:74338:20)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:74336:38)
    at PackageManager.activatePackage (<embedded>:25986:42)
    at config.transactAsync (<embedded>:25961:36)
    at Config.transactAsync (<embedded>:22574:28)
    at PackageManager.activatePackages (<embedded>:25959:23)
    at PackageManager.activate (<embedded>:25938:50)
    at loadStatePromise.loadState.then (<embedded>:1111:27)
    at <anonymous>:null:null

```

### Commands

```
```

### Non-Core Packages

**Comment by the-webguys** [comment]
Same thing for me, the moment i open Atom

**Comment by hasanparasteh** [comment]
`[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Ubuntu 18.04.1
**Thrown From**: [css-spy](https://github.com/stackroute/atom-css-spy) package 0.6.0


### Stack Trace

Failed to activate the css-spy package

```
At Cannot read property 'text.html.basic' of undefined

TypeError: Cannot read property 'text.html.basic' of undefined
    at Object.module.exports.watcherFunction (/packages/css-spy/lib/css-spy.coffee:25:10)
    at /packages/css-spy/lib/css-spy.coffee:17:8
    at Workspace.observeTextEditors (/usr/share/atom/resources/app/static/<embedded>:11:427889)
    at Object.activate (/packages/css-spy/lib/css-spy.coffee:16:39)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:2911558)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:2910970)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:2908601)
    at activationPromise.activationPromise.Promise (/usr/share/atom/resources/app/static/<embedded>:11:2910830)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/static/<embedded>:11:2910773)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:382481)
    at /usr/share/atom/resources/app/static/<embedded>:11:916639
    at r (/usr/share/atom/resources/app/static/<embedded>:11:911245)
    at o (/usr/share/atom/resources/app/static/<embedded>:14:1036521)
    at t.bufferStream (/usr/share/atom/resources/app/static/<embedded>:14:1036675)
    at Socket.e.on (/usr/share/atom/resources/app/static/<embedded>:14:1035277)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
     -4:56.1.0 intentions:highlight (input.hidden-input)
     -4:55.9.0 autocomplete-plus:activate (input.hidden-input)
     -4:54.1.0 intentions:highlight (input.hidden-input)
  3x -4:54 autocomplete-plus:activate (input.hidden-input)
     -4:52.2.0 editor:consolidate-selections (input.hidden-input)
     -4:52.2.0 core:cancel (input.hidden-input)
     -4:51.9.0 editor:consolidate-selections (input.hidden-input)
     -4:51.9.0 core:cancel (input.hidden-input)
  5x -3:04.9.0 core:backspace (input.hidden-input)
     -2:37 core:select-all (input.hidden-input)
     -2:34 core:confirm (input.hidden-input)
     -2:32.9.0 core:select-all (input.hidden-input)
     -2:32.5.0 core:cut (input.hidden-input)
     -2:30.6.0 core:select-all (input.hidden-input)
     -2:30.4.0 core:paste (input.hidden-input)
     -2:29 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-code-syntax 0.3.1 
atom-code-ui 0.4.4 
css-spy 0.6.0 
atom-ide-ui 0.13.0 
atom-live-server 2.3.0 
atom-path-intellisense 1.1.1 
autoclose-html 0.23.0 
autocomplete-modules 2.2.6 
autoprefixer 3.7.1 
busy-signal 1.4.3 
chameleon-ui 2.0.0 
chester-atom-syntax 0.3.2 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
css-snippets 1.1.0 
css-spy 0.6.0 
dracula-syntax 2.0.7 
dracula-ui 0.6.0 
emmet 2.4.3 
file-icons 2.1.26 
highlight-selected 0.14.0 
html-id-class-snippets 1.4.1 
html-to-css 0.2.2 
ide-css 0.3.2 
ide-html 0.4.2 
ide-php 0.7.17 
intentions 1.1.5 
jackhammer-syntax 1.1.0 
jquery-snippets 11.0.0 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
php-cs-fixer 4.1.1 
php-server 0.8.0 
platformio-ide-terminal 2.8.4 
run-command 0.5.0 
seti-syntax 1.2.0 
seti-ui 1.11.0 
tryhtml-atom-syntax 0.1.2 
tryhtml-atom-ui 0.2.0 
vertex-ui 0.11.0 
wakatime 7.0.7 
```
`
anyone knows how to fix this?

**Comment by avatec** [comment]
Same here. After second run - problem doesn't exists.
