### ISSUE TITLE
Failed to activate the css-spy package

### ISSUE THREAD

**Issue by quinteirosm** [stackroute/atom-css-spy#26]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [css-spy](https://github.com/stackroute/atom-css-spy) package 0.6.0

### Stack Trace

Failed to activate the css-spy package

```
At Cannot read property 'text.html.basic' of undefined

TypeError: Cannot read property 'text.html.basic' of undefined
    at Object.module.exports.watcherFunction (/packages/css-spy/lib/css-spy.coffee:43:48)
    at /packages/css-spy/lib/css-spy.coffee:25:24
    at Workspace.observeTextEditors (<embedded>:11:428374)
    at Object.activate (/packages/css-spy/lib/css-spy.coffee:23:45)
    at Package.activateNow (<embedded>:11:3175323)
    at measure (<embedded>:11:3174735)
    at Package.measure (<embedded>:11:3172366)
    at activationPromise.activationPromise.Promise (<embedded>:11:3174595)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:11:3174538)
    at PackageManager.activatePackage (<embedded>:11:382705)
    at config.transactAsync (<embedded>:11:382321)
    at Config.transactAsync (<embedded>:11:332491)
    at PackageManager.activatePackages (<embedded>:11:382271)
    at PackageManager.activate (<embedded>:11:381889)
    at t.loadState.then (<embedded>:1:696488)
    at <anonymous>:null:null

```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
css-spy 0.6.0 
drunken-php 0.2.4 
emmet 2.4.3 
ide-css 0.3.2 
ide-html 0.5.0 
intentions 1.1.5 
linter 2.3.0 
linter-spell 0.15.0 
linter-spell-javascript 0.9.0 
linter-ui-default 1.7.1 
```

**Comment by avatec** [comment]
Same here:

Cannot read property 'text.html.basic' of undefined
Hide Stack Trace
TypeError: Cannot read property 'text.html.basic' of undefined
    at Object.module.exports.watcherFunction (/Users/avatec/.atom/packages/css-spy/lib/css-spy.coffee:43:48)
    at /Users/avatec/.atom/packages/css-spy/lib/css-spy.coffee:25:24
    at Workspace.observeTextEditors (<embedded>:11:427450)
    at Object.activate (/Users/avatec/.atom/packages/css-spy/lib/css-spy.coffee:23:45)
    at Package.activateNow (<embedded>:11:3421604)
    at measure (<embedded>:11:3421016)
    at Package.measure (<embedded>:11:3418626)
    at activationPromise.activationPromise.Promise (<embedded>:11:3420876)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:11:3420819)
    at PackageManager.activatePackage (<embedded>:11:381612)
    at config.transactAsync (<embedded>:11:381228)
    at Config.transactAsync (<embedded>:11:331162)
    at PackageManager.activatePackages (<embedded>:11:381178)
    at PackageManager.activate (<embedded>:11:380728)
    at t.loadState.then (<embedded>:1:708815)

**Comment by VX1D** [comment]
TypeError: Cannot read property 'text.html.basic' of undefined
    at Object.module.exports.watcherFunction (C:\Users\dapla\.atom\packages\css-spy\lib\css-spy.coffee:43:48)
    at C:\Users\dapla\.atom\packages\css-spy\lib\css-spy.coffee:25:24
    at Workspace.observeTextEditors (<embedded>:11:428138)
    at Object.activate (C:\Users\dapla\.atom\packages\css-spy\lib\css-spy.coffee:23:45)
    at Package.activateNow (<embedded>:11:3405731)
    at measure (<embedded>:11:3405143)
    at Package.measure (<embedded>:11:3402753)
    at activationPromise.activationPromise.Promise (<embedded>:11:3405003)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:11:3404946)
    at PackageManager.activatePackage (<embedded>:11:382285)
    at <embedded>:11:937303
    at r (<embedded>:11:931909)
    at n (<embedded>:14:1128986)
    at ChildProcess.o.process.on.e (<embedded>:14:1129192)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)

**Comment by TheBdouilleur** [comment]
Me too:
Failed to activate the css-spy package

Cannot read property 'text.html.basic' of undefined

TypeError: Cannot read property 'text.html.basic' of undefined
    at Object.module.exports.watcherFunction (C:\Users\pmhue\.atom\packages\css-spy\lib\css-spy.coffee:43:48)
    at C:\Users\pmhue\.atom\packages\css-spy\lib\css-spy.coffee:25:24
    at Workspace.observeTextEditors (<embedded>:11:428138)
    at Object.activate (C:\Users\pmhue\.atom\packages\css-spy\lib\css-spy.coffee:23:45)
    at Package.activateNow (<embedded>:11:3405731)
    at measure (<embedded>:11:3405143)
    at Package.measure (<embedded>:11:3402753)
    at activationPromise.activationPromise.Promise (<embedded>:11:3405003)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:11:3404946)
    at PackageManager.activatePackage (<embedded>:11:382285)
    at config.transactAsync (<embedded>:11:381901)
    at Config.transactAsync (<embedded>:11:331549)
    at PackageManager.activatePackages (<embedded>:11:381851)
    at PackageManager.activate (<embedded>:11:381401)
    at t.loadState.then (<embedded>:1:736497)

**Comment by aliglelo** [comment]
same here:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 19.04
**Thrown From**: [css-spy](https://github.com/stackroute/atom-css-spy) package 0.6.0


### Stack Trace

Failed to activate the css-spy package

```
At Cannot read property 'text.html.basic' of undefined

TypeError: Cannot read property 'text.html.basic' of undefined
    at Object.module.exports.watcherFunction (/packages/css-spy/lib/css-spy.coffee:43:48)
    at /packages/css-spy/lib/css-spy.coffee:25:24
    at Workspace.observeTextEditors (<embedded>:11:428138)
    at Object.activate (/packages/css-spy/lib/css-spy.coffee:23:45)
    at Package.activateNow (<embedded>:11:3293263)
    at measure (<embedded>:11:3292675)
    at Package.measure (<embedded>:11:3290285)
    at activationPromise.activationPromise.Promise (<embedded>:11:3292535)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:11:3292478)
    at PackageManager.activatePackage (<embedded>:11:382285)
    at config.transactAsync (<embedded>:11:381901)
    at Config.transactAsync (<embedded>:11:331549)
    at PackageManager.activatePackages (<embedded>:11:381851)
    at PackageManager.activate (<embedded>:11:381401)
    at t.loadState.then (<embedded>:1:710322)

```

### Commands

```
```

### Non-Core Packages

```
atom-live-server 2.3.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
autosave-onchange 1.5.1 
busy-signal 2.0.1 
css-helper-snippets 0.3.0 
css-snippets 1.1.0 
css-spy 0.6.0 
emmet 2.4.3 
highlight-selected 0.16.0 
html-head-snippets 0.2.0 
html-tag-auto-complete 0.1.1 
intentions 1.1.5 
linter 2.3.1 
linter-eslint 8.5.5 
linter-spell-html 0.7.0 
linter-ui-default 1.8.0 
php-server 0.8.0 
pigments 0.40.2 
styri-syntax 1.0.0 
```

**Comment by Pinan32** [comment]
TypeError: Cannot read property 'text.html.basic' of undefined
    at Object.module.exports.watcherFunction (C:\Users\User\.atom\packages\css-spy\lib\css-spy.coffee:43:48)
    at C:\Users\User\.atom\packages\css-spy\lib\css-spy.coffee:25:24
    at Workspace.observeTextEditors (<embedded>:11:428422)
    at Object.activate (C:\Users\User\.atom\packages\css-spy\lib\css-spy.coffee:23:45)
    at Package.activateNow (<embedded>:11:3313556)
    at measure (<embedded>:11:3312968)
    at Package.measure (<embedded>:11:3310578)
    at activationPromise.activationPromise.Promise (<embedded>:11:3312828)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:11:3312771)
    at PackageManager.activatePackage (<embedded>:11:382554)
    at config.transactAsync (<embedded>:11:382170)
    at Config.transactAsync (<embedded>:11:331818)
    at PackageManager.activatePackages (<embedded>:11:382120)
    at PackageManager.activate (<embedded>:11:381670)
    at t.loadState.then (<embedded>:1:749538)

**Comment by wirehiker** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 19.10
**Thrown From**: [css-spy](https://github.com/stackroute/atom-css-spy) package 0.6.0


### Stack Trace

Failed to activate the css-spy package

```
At Cannot read property 'text.html.basic' of undefined

TypeError: Cannot read property 'text.html.basic' of undefined
    at Object.module.exports.watcherFunction (/packages/css-spy/lib/css-spy.coffee:43:48)
    at /packages/css-spy/lib/css-spy.coffee:25:24
    at Workspace.observeTextEditors (<embedded>:11:428422)
    at Object.activate (/packages/css-spy/lib/css-spy.coffee:23:45)
    at Package.activateNow (<embedded>:11:3206593)
    at measure (<embedded>:11:3206005)
    at Package.measure (<embedded>:11:3203615)
    at activationPromise.activationPromise.Promise (<embedded>:11:3205865)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:11:3205808)
    at PackageManager.activatePackage (<embedded>:11:382554)
    at <embedded>:11:940004
    at r (<embedded>:11:934610)
    at n (<embedded>:14:1128169)
    at t.bufferStream (<embedded>:14:1128323)
    at Socket.e.on (<embedded>:14:1126925)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close (net.js:606:12)

```

### Commands

```
     -7:21.9.0 core:backspace (input.hidden-input)
  6x -3:23.9.0 core:move-left (input.hidden-input)
  6x -3:21.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-js-console 1.2.2 
atom-monokai 0.10.9 
atom-smart-template 0.3.2 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
autoprefixer 4.1.0 
autosave-onchange 1.5.1 
busy-signal 2.0.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
color-picker 2.3.0 
console-panel 0.3.1 
css-color-name 0.4.0 
css-spy 0.6.0 
csslint 1.2.0 
darcula-syntax 0.2.1 
emmet 2.4.3 
file-icons 2.1.36 
highlight-selected 0.16.0 
hyperclick 0.1.5 
intentions 1.1.5 
jquery-snippets 11.0.0 
js-refactor 0.8.1 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-jshint 3.1.17 
linter-ui-default 1.8.0 
minimap 4.29.9 
nuclide-format-js 0.0.47 
open-in-browsers 0.0.30 
open-terminal-here 2.3.2 
p5js-snippets 0.4.4 
p5js-syntax 0.1.1 
pigments 0.40.2 
pinegrow-atom 0.3.1 
refactor 0.11.5 
script 3.25.0 
Sublime-Style-Column-Selection 1.7.5 
sync-settings 0.8.6 
todo-show 2.3.2 
```
