### ISSUE TITLE
Failed to activate the css-spy package

### ISSUE THREAD

**Issue by gluckey23** [stackroute/atom-css-spy#27]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [css-spy](https://github.com/stackroute/atom-css-spy) package 0.6.0

### Stack Trace

Failed to activate the css-spy package

```
At Cannot read property 'text.html.basic' of undefined

TypeError: Cannot read property 'text.html.basic' of undefined
    at Object.module.exports.watcherFunction (/packages/css-spy/lib/css-spy.coffee:43:48)
    at /packages/css-spy/lib/css-spy.coffee:25:24
    at Workspace.observeTextEditors (<embedded>:11:428320)
    at Object.activate (/packages/css-spy/lib/css-spy.coffee:23:45)
    at Package.activateNow (<embedded>:11:3326876)
    at measure (<embedded>:11:3326288)
    at Package.measure (<embedded>:11:3323898)
    at activationPromise.activationPromise.Promise (<embedded>:11:3326148)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:11:3326091)
    at PackageManager.activatePackage (<embedded>:11:382452)
    at o.forEach.e (<embedded>:11:377618)
    at Array.forEach (<anonymous>:null:null)
    at disabledPackagesSubscription.disabledPackagesSubscription.config.onDidChange (<embedded>:11:377602)
    at emitter.on (<embedded>:11:334653)
    at Function.simpleDispatch (<embedded>:11:1214120)
    at Emitter.emit (<embedded>:11:1215561)
    at Config.emitChangeEvent (<embedded>:11:337141)
    at Config.setRawValue (<embedded>:11:334381)
    at Config.set (<embedded>:11:330175)
    at Object.updateSettings (/packages/sync-settings/lib/utils/utils.js:150:16)
    at SyncSettings.restore (/packages/sync-settings/lib/sync-settings.js:281:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

### Commands

```
     -0:35.7.0 sync-settings:check-backup (input.hidden-input)
     -0:10.4.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-visual-studio-code-ui)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-javascript 1.3.0 
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-runner 2.7.1 
atom-ternjs 0.20.0 
atom-visual-studio-code-ui 2.1.0 
block-comment 0.4.3 
busy-signal 2.0.1 
cdnjs 1.5.5 
code-peek 1.4.21 
codyhouse-snippets 0.14.0 
color-picker 2.3.0 
css-spy 0.6.0 
double-tag 1.7.0 
emmet 2.4.3 
highlight-selected 0.17.0 
html-to-css 0.2.2 
hyperclick 0.1.5 
intentions 1.1.5 
javascript-snippets 1.2.1 
linter 2.3.1 
linter-eslint 8.5.5 
linter-htmlhint 1.6.3 
linter-jshint 3.1.19 
linter-ui-default 1.8.1 
local-history 4.3.1 
minimap 4.29.9 
open-in-browsers 0.0.30 
pigments 0.40.2 
sort-lines 0.19.0 
split-diff 1.6.1 
sync-settings 4.3.2 
```

**Comment by kangarooo** [comment]
Me too

**Comment by RicardoGAlonso** [comment]
SAme for me.

**Comment by TheCrescentKing** [comment]
Same here.

**Comment by amoako-franque** [comment]
**Same here. Any fix**

**Comment by MusingComet** [comment]
Same here, any fix?

**Comment by charliez** [comment]
Same here

**Comment by p3t3r67x0** [comment]
Same here, anyone has an idea?

**Comment by Craftplacer** [comment]
Same here

**Comment by WhiplashGamz** [comment]
Same Here

**Comment by pavakpaul** [comment]
Same here

**Comment by Rayan84** [comment]
add me to the list

**Comment by ghost** [comment]
oh god some things are gonna have to be fixed

**Comment by K2adir** [comment]
same

**Comment by ferrval** [comment]
What about a MacBook version?

**Comment by stepanjakl** [comment]
Any update about this?

**Comment by FreshImmuc** [comment]
Same

**Comment by Hernewson** [comment]
Does anyone solve the issue??
