### ISSUE TITLE
Uncaught TypeError: Cannot read property '2' of null

### ISSUE THREAD

**Issue by smiga287** [stackroute/atom-css-spy#4]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Microsoft Windows 10 Pro
**Thrown From**: [css-spy](https://github.com/stackroute/atom-css-spy) package, v0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property '2' of null

```
At /C:/Users/aleks/.atom/packages/css-spy/lib/css-spy.coffee:83

TypeError: Cannot read property '2' of null
    at file:///C:/Users/aleks/.atom/packages/css-spy/lib/css-spy.coffee:54:84
    at file:///C:/Users/aleks/.atom/packages/css-spy/lib/css-spy.coffee:51:13
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\aleks\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\aleks\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\aleks\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1321:25
```

### Commands

```
     -0:06.1.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:05.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:05.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:05.7.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:03.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:03.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:03.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:03.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:03.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:03.1.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:01.6.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:01.6.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:01.6.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:01.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:01.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:01.5.0 editor:indent (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.13
atom-material-syntax, v0.2.10
atom-material-ui, v0.8.0
autoclose-html, v0.20.0
color-picker, v2.1.1
counter, v0.3.3
css-snippets, v0.9.0
css-spy, v0.5.0
html-id-class-snippets, v1.4.1
pigments, v0.22.1

# Dev
No dev packages
```

**Comment by prateekreddy** [comment]
Hi @smiga287,

The error should be fixed now in v0.5.1 66da115d31631249ae145ac2aacf839ab255ca0d
