### ISSUE TITLE
Failed to load the css-spy package

### ISSUE THREAD

**Issue by granteagon** [stackroute/atom-css-spy#6]
[Enter steps to reproduce below:]

1. cd ~/.atom/packages/some-package
2. atom -d .

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.5
**Thrown From**: [css-spy](https://github.com/stackroute/atom-css-spy) package, v0.5.1

### Stack Trace

Failed to load the css-spy package

```
At ENOENT: no such file or directory, open '/Users/grant/.atom/dev/packages,/Users/grant/.atom/packages/css-spy/grammar/class-add.cson'

Error: ENOENT: no such file or directory, open '/Users/grant/.atom/dev/packages,/Users/grant/.atom/packages/css-spy/grammar/class-add.cson'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at CSON.parseCSONFile (/Users/grant/.atom/packages/css-spy/node_modules/cson/out/lib/cson.js:332:23)
    at CSON.load (/Users/grant/.atom/packages/css-spy/node_modules/cson/out/lib/cson.js:141:19)
    at Object.<anonymous> (/Users/grant/.atom/packages/css-spy/lib/css-spy.coffee:7:18)
    at Object.<anonymous> (/Users/grant/.atom/packages/css-spy/lib/css-spy.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
autoclose-html, v0.23.0
color-picker, v2.1.1
css-specificity, v0.2.2
css-spy, v0.5.1
editor-stats, v0.17.0
emmet, v2.4.2
highlight-selected, v0.11.2
imdone-atom, v1.3.27
language-babel, v2.15.5
linter, v1.11.3
linter-csslint, v1.3.2
linter-eslint, v7.0.0
linter-sass-lint, v1.1.2
linter-scss-lint, v2.5.1
pigments, v0.24.4
project-manager, v2.7.6
save-session, v0.15.7
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by granteagon** [comment]
This looks like something dumb I did, trying to develop a package but no dev packages exist.  I'll close.  Feel free to reopen, but I'm getting lots of errors from other packages as well so I think it's me.

**Comment by cleverappdesign** [comment]
I have the same issue as well. I did the manual install and throw me an error message after I restarted atom.

ENOENT: no such file or directory, open '/Users/CindyTan/.atom/packages/css-spy/grammar/class-add.cson'
